# Generated by Django 4.1.3 on 2023-05-19 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pinax_notifications', '0003_alter_noticequeuebatch_id_alter_noticesetting_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticesetting',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, help_text='Key to use for unsubscribe to the notification', verbose_name='key'),
        ),
        migrations.AlterField(
            model_name='noticesetting',
            name='medium',
            field=models.PositiveSmallIntegerField(choices=[(0, 'email'), (1, 'push'), (2, 'in_app'), (3, 'telegram')], verbose_name='medium'),
        ),
        migrations.CreateModel(
            name='NoticeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.PositiveSmallIntegerField(choices=[(0, 'email'), (1, 'push'), (2, 'in_app'), (3, 'telegram')], verbose_name='medium')),
                ('when', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('notice_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinax_notifications.noticetype', verbose_name='notice type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
